# Generated by Django 2.0 on 2017-12-21 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('return_url', models.URLField(max_length=80)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_secret', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
